sudo: required
language: python
python:
  - "2.7"
  
# command to install dependencies
install: "pip install pylint virtualenv"

# command to build
script: 
  - ./dev release
  - ./dev tests

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install clang
