sudo: required
language: python
python:
  - "2.7"
  
# command to install dependencies
install: "pip install pylint virtualenv setuptools"
 
# command to build
script: 
  - sudo apt-get -qq update
  - sudo apt-get install clang
  - ./dev release
  - ./dev tests
